// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5oI556H6U5JmBjPHwIRrT6s8WtyNOuog',
    appId: '1:31476427074:web:1fb2b5e58df075d215c0db',
    messagingSenderId: '31476427074',
    projectId: 'pocopoco-7b9ab',
    authDomain: 'pocopoco-7b9ab.firebaseapp.com',
    storageBucket: 'pocopoco-7b9ab.firebasestorage.app',
    measurementId: 'G-Y6DNKV5CWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1_6FxMS16sm67HCciqbJQvP5ZuqVMt5I',
    appId: '1:31476427074:android:ec4997ab1c4e983215c0db',
    messagingSenderId: '31476427074',
    projectId: 'pocopoco-7b9ab',
    storageBucket: 'pocopoco-7b9ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMSMMaoiKUINnGXqNUGHRscUct9fcNVAo',
    appId: '1:31476427074:ios:088fcecb00b12d1715c0db',
    messagingSenderId: '31476427074',
    projectId: 'pocopoco-7b9ab',
    storageBucket: 'pocopoco-7b9ab.firebasestorage.app',
    iosBundleId: 'com.mizoishun.pocopoco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMSMMaoiKUINnGXqNUGHRscUct9fcNVAo',
    appId: '1:31476427074:ios:6d9f0cef969a9e4415c0db',
    messagingSenderId: '31476427074',
    projectId: 'pocopoco-7b9ab',
    storageBucket: 'pocopoco-7b9ab.firebasestorage.app',
    iosBundleId: 'com.example.poco',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5oI556H6U5JmBjPHwIRrT6s8WtyNOuog',
    appId: '1:31476427074:web:3e5b22f6b727135015c0db',
    messagingSenderId: '31476427074',
    projectId: 'pocopoco-7b9ab',
    authDomain: 'pocopoco-7b9ab.firebaseapp.com',
    storageBucket: 'pocopoco-7b9ab.firebasestorage.app',
    measurementId: 'G-CFZDCMH3ZT',
  );
}
